// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvhukwtlqpspsnucusea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2aHVrd3RscXBzcHNudWN1c2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTUzNTEsImV4cCI6MjA2ODc3MTM1MX0.Ja_DfwpeYwtR4yRIfUI8QE1GT7AbrC7GnmodtZa1Q_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});